### ISSUE TITLE
The instructions in the README appear cut off

### ISSUE THREAD

**Issue by Potato-Matic** [kathamer/DebianKindle#15]
Hi,

It looks like the instructions for how to install debian are cut off.

They stop during the "Downgrade your Kindle's operating system" section after explaining how to find your device's model and don't get to how to do the downgrade. I can kind of see how things would progress from looking at other rooting guides, but it's pure guesswork. (especially given all the different models and revisions)

There's also little explanation on how to use the files in the repo. I can kind of guess at it from reading them (it looks like one has to be run on a debian system, and two other have to be somehow copied to and run under the kindle's linux?)

A bit more explanation in this area would be really helpful.

Thanks for putting this together,
    -Matt

**Comment by Paulpanther** [comment]
Seems to be deleted in f63e8cb. I'm going to try to put it together in a new PR. But I can't verify if it works because I don't have a Kindle
